{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spark-history-server.fullname" . }}
  labels:
    {{- include "spark-history-server.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spark-history-server.fullname" . }}
  labels:
    {{- include "spark-history-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spark-history-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-history-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
